services:
  job_search_bot:
    build:
      context: .
      dockerfile: Dockerfile

    network_mode: host

    environment:
      - "JAVA_OPTS="

    restart: always
    command: ["java", "-jar", "/app.jar"]